# Generated by Django 5.0.4 on 2024-04-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("make", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("fuel_type", models.CharField(max_length=50)),
                ("transmission_type", models.CharField(max_length=50)),
                ("oil_type", models.CharField(max_length=50)),
                ("tire_size", models.CharField(max_length=50)),
            ],
        ),
    ]
